# Streamlit secrets template for AI Patent Analyst

# ---------- Optional app metadata ----------
APP_TITLE = ""
DEBUG_MODE = ""  # "True" or "False"

# ---------- BigQuery configuration ----------
GOOGLE_CLOUD_PROJECT_ID = ""
BQ_DATASET_ID = ""
BQ_LOCATION = ""  # e.g., "US" or your region

# Optional explicit environment.
# APP_ENV = "prod"


[gcp_service_account]
# Keep all values as strings.

type = ""
project_id = ""
private_key_id = ""
private_key = """ 
"""
client_email = ""
client_id = ""
auth_uri = ""
token_uri = ""
auth_provider_x509_cert_url = ""
client_x509_cert_url = ""
universe_domain = ""  # usually "googleapis.com"
